<?php
/**
 * Stage 5 seed — run via wp-cli after deploy:
 * php8.3 wp-cli.phar --path=PATH eval-file wp-content/seed-stage5.php
 * Delete after use. Seeds pages + CSS.
 */
if (PHP_SAPI !== 'cli') { http_response_code(403); exit("CLI only\n"); }
exit("Deprecated. Use scripts/prod-seed-stage7.php\n");
$_SERVER['HTTP_HOST'] = 'localhost';
require_once dirname(__DIR__) . '/wp-load.php';
echo "=== Stage 5 Seed ===\n";
$au = site_url('/wp-content/uploads/dom-expert-assets/');
function i2($f,$a='',$c='de-asset',$d=false){global $au;$alt=$d?'alt="" aria-hidden="true"':'alt="'.esc_attr($a).'"';return "<img class=\"$c\" src=\"$au$f\" $alt loading=lazy decoding=async>";}
function sp($s,$t,$c,$ps=''){$p=0;if($ps){$pp=get_page_by_path($ps);$p=$pp?(int)$pp->ID:0;}$sl=basename($s);$fp=$ps?$ps.'/'.$sl:$sl;$ex=get_page_by_path($fp);if($ex){wp_update_post(['ID'=>$ex->ID,'post_content'=>$c,'post_parent'=>$p]);echo"  Updated /$fp\n";}else{$id=wp_insert_post(['post_type'=>'page','post_status'=>'publish','post_title'=>$t,'post_name'=>$sl,'post_parent'=>$p,'post_content'=>$c]);echo"  Created /$fp ID $id\n";}}
function c2($i,$t,$x,$u='#'){$g=i2($i,'','de-icon',true);return "<article class=\"de-card de-card--tool\"><div class=\"de-iconbox\">$g</div><h3>$t</h3><p>$x</p><a class=\"de-link\" href=\"$u\">Подробнее →</a></article>";}
function t2($i,$n,$l){$g=i2($i,'','de-icon',true);return"<div class=\"de-trust\"><div class=\"de-iconbox de-iconbox--gold\">$g</div><strong>$n</strong><span>$l</span></div>";}
function p2($p,$st,$pr,$rk,$rc='attention'){$im=i2($p,'Плейсхолдер','de-property__img');$si=i2('status/verified.svg','','de-mini',true);return"<article class=\"de-property\"><div class=\"de-property__media\">$im<span class=\"de-status\">$si$st</span></div>...";}

$home = '<div class="de-shell"><section class="de-hero"><div><span class="de-eyebrow">Экспертный сервис недвижимости</span><h1>Продать или купить квартиру без потерь и скрытых рисков</h1><p class="de-lead">Сначала — бесплатный диагностический результат. Затем — объяснение рисков, сохранение прогресса и консультация по следующему безопасному шагу.</p><div class="de-actions"><a class="de-btn de-btn--green" href="/sell/estimate/">Оценить квартиру</a><a class="de-btn de-btn--white" href="/buyers/risk-check/">Проверить объект</a></div></div><figure class="de-hero__poster">'.i2('posters/hero-main-desktop.svg','Эксперт по недвижимости: визуальный постер главной').'</figure></section><section class="de-section"><div class="de-paths"><a class="de-card de-card--dark de-card--path" href="/sell/"><div class="de-iconbox">'.i2('paths/seller-home.svg','','de-icon',true).'</div><h2>Продаю квартиру</h2><p>Оценка, фото-чек, документы и стратегия продажи.</p><div class="de-link">Начать →</div></a><a class="de-card de-card--path" href="/buyers/"><div class="de-iconbox">'.i2('paths/buyer-key.svg','','de-icon',true).'</div><h2>Покупаю квартиру</h2><p>Risk-check, каталог, сравнение и проверка документов.</p><div class="de-link">Начать →</div></a></div></section><section class="de-section"><div class="de-trust-strip">'.t2('trust/experience.svg','12+','лет практики').t2('trust/checked-properties.svg','2800+','проверок объектов').t2('trust/rating.svg','4.8★','средний рейтинг').t2('trust/shield.svg','100%','независимый подход').'</div></section><section class="de-section de-section--muted"><span class="de-eyebrow">Польза до заявки</span><h2>Инструменты, которые возвращают пользователя к решению</h2><p class="de-lead">Выберите сценарий и получите результат до контакта.</p><div class="de-grid de-grid-3">'.c2('paths/estimate.svg','Оценка цены','Диапазон цены и факторы уверенности без телефона.','/sell/estimate/').c2('paths/photo-check.svg','AI фото-чек','Какие фотографии снижают доверие и цену.','/sell/photo-check/').c2('paths/risk-check.svg','Risk-check','Что проверить до задатка: документы, дом, район.','/buyers/risk-check/').c2('paths/compare.svg','Сравнение','2–4 объекта по цене, рискам и качеству решения.','/compare/').c2('paths/developer-check.svg','Застройщик','Проекты, задержки, эскроу и рейтинг.','/developers/').c2('paths/legal-check.svg','Документы','Обременения, основания права, история объекта.','/buyers/risk-check/').'</div></section></div>';
$sell = '<div class="de-shell"><section class="de-hero"><div><span class="de-eyebrow">Для продавцов</span><h1>Продайте квартиру по стратегии, а не по догадке</h1><p class="de-lead">Оценка диапазона цены, фото-чек, диагностика готовности и план подготовки к продаже.</p><div class="de-actions"><a class="de-btn de-btn--green" href="/sell/estimate/">Оценить квартиру</a><a class="de-btn de-btn--white" href="/sell/diagnostic/">Полная диагностика</a></div></div><figure class="de-hero__poster">'.i2('posters/seller-hero.svg','Постер: продайте без потери цены').'</figure></section><section class="de-section"><div class="de-grid de-grid-3">'.c2('paths/estimate.svg','1. Быстрая оценка','Диапазон цены без контакта и ложной точности.','/sell/estimate/').c2('paths/seller-diagnostic.svg','2. Diagnostic','10 точек потери денег и план действий.','/sell/diagnostic/').c2('paths/strategy.svg','3. Стратегия','Подготовка, показы, торг и переговоры.','/sell/diagnostic/').'</div></section></div>';
$buyers = '<div class="de-shell"><section class="de-hero"><div><span class="de-eyebrow">Для покупателей</span><h1>Проверьте объект до задатка и сравните альтернативы</h1><p class="de-lead">Risk-check, каталог, сравнение объектов и проверка застройщика помогают понять не только цену, но и последствия покупки.</p><div class="de-actions"><a class="de-btn de-btn--green" href="/buyers/risk-check/">Проверить риски</a><a class="de-btn de-btn--white" href="/buyers/catalog/">Смотреть каталог</a></div></div><figure class="de-hero__poster">'.i2('posters/buyer-hero.svg','Постер: покупайте безопасно').'</figure></section><section class="de-section"><div class="de-grid de-grid-3">'.c2('paths/risk-check.svg','Risk-check','3–5 пунктов, которые надо проверить до сделки.','/buyers/risk-check/').c2('paths/compare.svg','Сравнение','Сравнить цену, риски и следующий шаг.','/compare/').c2('paths/legal-check.svg','Юридическая проверка','Права, обременения и история объекта.','/buyers/risk-check/').'</div></section></div>';
$estimate = '<div class="de-shell"><section class="de-hero"><div><span class="de-eyebrow">Оценка без контакта</span><h1>Получите первичный диапазон цены квартиры</h1><p class="de-lead">Введите параметры — покажем диапазон и факторы, которые могут поднять или снизить цену.</p></div><figure class="de-hero__poster">'.i2('posters/estimate-result.svg','Постер: рыночная оценка готова').'</figure></section><section class="de-section"><div class="de-tool-result"><div class="de-form-card"><div class="de-field">'.i2('forms/location.svg','','de-icon',true).'<span>Адрес квартиры</span></div><div class="de-field">'.i2('property/area.svg','','de-icon',true).'<span>Площадь и комнаты</span></div><div class="de-field">'.i2('forms/calendar.svg','','de-icon',true).'<span>Год и состояние</span></div><a class="de-btn de-btn--green" href="#">Рассчитать диапазон</a></div></div></section></div>';
$risk = '<div class="de-shell"><section class="de-hero"><div><span class="de-eyebrow">Risk-check</span><h1>Проверьте, что важно до задатка</h1><p class="de-lead">Адрес, дом, район, продавец или застройщик.</p></div><figure class="de-hero__poster">'.i2('posters/risk-report.svg','Постер: проверка рисков').'</figure></section><section class="de-section"><div class="de-risk-panel"><h2>Risk-score: 56 — требует внимания</h2><div class="de-risk-items"><div class="de-risk-item">'.i2('risk/noise-medium.svg','Шум: средний','').'<div><strong>Шум: средний</strong><p>Причина: магистраль рядом.</p></div></div><div class="de-risk-item">'.i2('risk/ecology-low.svg','Экология: низкий','').'<div><strong>Экология: низкий</strong><p>Нет красных зон.</p></div></div></div></div></section></div>';

sp('sell','Продать квартиру',$sell);
sp('buyers','Купить квартиру',$buyers);
sp('sell/estimate','Оценка квартиры',$estimate,'sell');
sp('buyers/risk-check','Проверка рисков',$risk,'buyers');
$f=get_page_by_path('preview-home');if($f){update_option('show_on_front','page');update_option('page_on_front',(int)$f->ID);}
echo "CSS not set — paste from local custom_css post\n";
echo "ALL PAGES SEEDED\n";
